export const exchanges = {
    ARGENBTC: {
        key: 'ARGENBTC',
        value: 1,
        title: 'ArgenBTC',
        coin: 'BTC, DAI',
        fiat: 'ARS',
        resourcepath: '/argenbtc',
    },
    BELO: {
        key: 'BELO',
        value: 2,
        title: 'Belo',
        coin: 'BTC, ETH, DAI, USDT, USDC',
        fiat: 'ARS',
        resourcepath: '/belo',
    },
    BITEX: {
        key: 'BITEX',
        value: 3,
        title: 'Bitex',
        coin: 'BTC, ETH, DAI, USDC, USDT',
        fiat: 'ARS',
        resourcepath: '/bitex',
    },
    BITMONEDERO: {
        key: 'BITMONEDERO',
        value: 4,
        title: 'Bitmonedero',
        coin: 'BTC',
        fiat: 'ARS',
        resourcepath: '/bitmonedero',
    },
    BITSO: {
        key: 'BITSO',
        value: 5,
        title: 'Bitso',
        coin: 'BTC, DAI',
        fiat: 'ARS, BRL, MXN, TUSD, DAI, USD',
        resourcepath: '/bitso',
    },
    BUDA: {
        key: 'BUDA',
        value: 6,
        title: 'Buda',
        coin: 'BTC, ETH, BCH, LTC',
        fiat: 'ARS, CLP, COP, PEN',
        resourcepath: '/buda',
    },
    BUENBIT: {
        key: 'BUENBIT',
        value: 7,
        title: 'Buenbit',
        coin: 'BTC, ETH, DAI, ADA, BNB, MATIC',
        fiat: 'ARS, PEN, USD',
        resourcepath: '/buenbit',
    },
    CALYPSO_EXCHANGE_P2P: {
        key: 'CALYPSO_EXCHANGE_P2P',
        value: 8,
        title: 'Calypso Exchange P2P',
        coin: 'BTC, ETH, DAI, USDT, LTC, BCH',
        fiat: 'ARS, USD',
        resourcepath: '/calypso',
    },
    COPTER: {
        key: 'COPTER',
        value: 9,
        title: 'Copter',
        coin: 'BTC, ETH, XLM',
        fiat: 'ARS, USDC',
        resourcepath: '/copter',
    },
    CRIPTOFACIL: {
        key: 'CRIPTOFACIL',
        value: 10,
        title: 'CriptoFácil',
        coin: 'BTC, ETH, USDT, BCH, LTC, ADA',
        fiat: '',
        resourcepath: '/criptofacil',
    },
    CRYPTOMKT: {
        key: 'CRYPTOMKT',
        value: 11,
        title: 'CryptoMKT',
        coin: 'BTC, ETH, EOS',
        fiat: 'ARS, BRL, CLP',
        resourcepath: '/cryptomkt',
    },
    DECRYPTO: {
        key: 'DECRYPTO',
        value: 12,
        title: 'Decrypto',
        coin: 'BTC, USDT, DAI',
        fiat: 'ARS, PEN, USD',
        resourcepath: '/decrypto',
    },
    DOMITAI: {
        key: 'DOMITAI',
        value: 13,
        title: 'Domitai',
        coin: 'BTC, ETH, USDT, USDC, LTC, BCH',
        fiat: 'MXN',
        resourcepath: '/domitai',
    },
    FIWIND: {
        key: '',
        value: 14,
        title: 'Fiwind',
        coin: '',
        fiat: 'ARS, USD',
        resourcepath: '/fiwind',
    },
    KRIPTON_MARKET: {
        key: 'KRIPTON_MARKET',
        value: 15,
        title: 'Kripton Market',
        coin: 'BTC, DOC, USDT',
        fiat: '',
        resourcepath: '/kriptonmarket',
    },
    LATAMEX: {
        key: 'LATAMEX',
        value: 16,
        title: 'Latamex',
        coin: 'BTC, ETH, DAI, USDT, LTC',
        fiat: 'ARS, BRL, MXN',
        resourcepath: '/latamex',
    },
    LEMONCASH: {
        key: 'LEMONCASH',
        value: 17,
        title: 'LemonCash',
        coin: 'BTC, ETH, USDT, UNI',
        fiat: '',
        resourcepath: '/lemoncash',
    },
    LETSBIT: {
        key: 'LETSBIT',
        value: 18,
        title: 'Let is Bit',
        coin: 'BTC, ETH, DAI, USDT, USDP, ADA, LINK, EOS, UNI',
        fiat: 'ARS, USD, EUR',
        resourcepath: '/letsbit',
    },
    ORIONX: {
        key: 'ORIONX',
        value: 19,
        title: 'Orionx',
        coin: 'BTC, ETH, DAI, USDT, BNB, BCH, LTC, XLM, XRP',
        fiat: 'CLP',
        resourcepath: '/orionx',
    },
    PLUSCRYPTO: {
        key: 'PLUSCRYPTO',
        value: 20,
        title: 'Plus Crypto',
        coin: 'BTC, ETH, DAI, USDC, USDT, PAXG, UNI, BCH, XRP, LINK, LTC',
        fiat: 'ARS',
        resourcepath: '/pluscrypto',
    },
    RIPIO: {
        key: 'RIPIO',
        value: 21,
        title: 'Ripio',
        coin: 'BTC, ETH, DAI, USDC, LTC, UNI, LINK',
        fiat: 'ARS, BRL, MXN',
        resourcepath: '/ripio',
    },
    RIPIO_EXCHANGE: {
        key: 'RIPIO_EXCHANGE',
        value: 22,
        title: 'Ripio Exchange',
        coin: 'BTC, ETH, DAI, USDC, BCH',
        fiat: 'ARS, BRL, USDC, DAI',
        resourcepath: '/ripioexchange',
    },
    SATOSHITANGO: {
        key: 'SATOSHITANGO',
        value: 23,
        title: 'SatoshiTango',
        coin: 'BTC, ETH, DAI, USDC, XRP, BCH, LTC, ADA, SOL, XLM',
        fiat: 'ARS, CLP, MXN, PEN, USD',
        resourcepath: '/satoshitango',
    },
    TIENDACRYPTO: {
        key: 'TIENDACRYPTO',
        value: 24,
        title: 'TiendaCrypto',
        coin: 'ETH, DAI',
        fiat: 'ARS',
        resourcepath: '/tiendacrypto',
    },
    UNIVERSALCOINS: {
        key: 'UNIVERSALCOINS',
        value: 25,
        title: 'UniversalCoins',
        coin: 'BTC, ETH, USDT, XRP, BCH, LTC, EOS',
        fiat: 'ARS, USD',
        resourcepath: '/universalcoins',
    },
    VIBRANT: {
        key: 'VIBRANT',
        value: 26,
        title: 'Vibrant',
        coin: 'USDC, XLM',
        fiat: 'ARS',
        resourcepath: '/vibrant',
    },
    VITA_WALLET: {
        key: 'VITA_WALLET',
        value: 27,
        title: 'Vita Wallet',
        coin: 'BTC',
        fiat: 'CLP',
        resourcepath: '/vitawallet',
    },
}